//! `.env` parsing and PUBLIC / SECRET classification for import, plus
//! `.env.example` generation for export.

use crate::model::{Variable, VariableKind};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DotenvEntry {
    pub name: String,
    pub value: String,
    pub line: usize,
}

/// Parse a dotenv file. Supports `KEY=value`, `export KEY=value`, single/double
/// quotes (with `\n`, `\"` escapes in double quotes), `#` comments, blank lines.
/// Invalid lines are skipped and reported by line number.
pub fn parse(text: &str) -> (Vec<DotenvEntry>, Vec<usize>) {
    let mut entries = Vec::new();
    let mut invalid = Vec::new();
    for (idx, raw) in text.lines().enumerate() {
        let line_no = idx + 1;
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let line = line.strip_prefix("export ").map(str::trim_start).unwrap_or(line);
        let Some((name, rest)) = line.split_once('=') else {
            invalid.push(line_no);
            continue;
        };
        let name = name.trim();
        if !is_valid_name(name) {
            invalid.push(line_no);
            continue;
        }
        let value = parse_value(rest.trim());
        entries.push(DotenvEntry {
            name: name.to_string(),
            value,
            line: line_no,
        });
    }
    (entries, invalid)
}

fn is_valid_name(name: &str) -> bool {
    let mut chars = name.chars();
    matches!(chars.next(), Some(c) if c.is_ascii_alphabetic() || c == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn parse_value(raw: &str) -> String {
    if let Some(inner) = raw.strip_prefix('"') {
        // Double-quoted: up to the closing unescaped quote, with escapes.
        let mut out = String::new();
        let mut chars = inner.chars();
        while let Some(c) = chars.next() {
            match c {
                '\\' => match chars.next() {
                    Some('n') => out.push('\n'),
                    Some('t') => out.push('\t'),
                    Some('r') => out.push('\r'),
                    Some(other) => out.push(other),
                    None => out.push('\\'),
                },
                '"' => break,
                other => out.push(other),
            }
        }
        return out;
    }
    if let Some(inner) = raw.strip_prefix('\'') {
        return inner.split('\'').next().unwrap_or("").to_string();
    }
    // Unquoted: strip trailing comment.
    let value = match raw.find(" #") {
        Some(i) => &raw[..i],
        None => raw,
    };
    value.trim().to_string()
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize)]
#[serde(rename_all = "UPPERCASE")]
pub enum Suggestion {
    Public,
    Secret,
    /// Looks like it *might* be sensitive (`*_KEY`, `*_URL` with credentials, ...).
    Review,
}

/// Suggest a kind from the name and value. The user confirms the final choice.
pub fn classify(name: &str, value: &str) -> Suggestion {
    let n = name.to_ascii_uppercase();
    if n.starts_with("NEXT_PUBLIC_")
        || n.starts_with("VITE_")
        || n.starts_with("PUBLIC_")
        || n.starts_with("EXPO_PUBLIC_")
        || n.starts_with("REACT_APP_")
        || n.starts_with("NUXT_PUBLIC_")
    {
        return Suggestion::Public;
    }
    let secret_markers = [
        "SECRET",
        "TOKEN",
        "PASSWORD",
        "PASSWD",
        "PRIVATE",
        "CREDENTIAL",
        "API_KEY",
        "APIKEY",
        "ACCESS_KEY",
        "SIGNING",
        "SALT",
        "DSN",
    ];
    if secret_markers.iter().any(|m| n.contains(m)) {
        return Suggestion::Secret;
    }
    // A URL that embeds credentials is a secret regardless of its name.
    if value.contains("://") && value.contains('@') && value.contains(':') {
        return Suggestion::Secret;
    }
    if n.ends_with("_KEY") || n.contains("AUTH") || n.contains("CERT") {
        return Suggestion::Review;
    }
    let plain = [
        "NODE_ENV",
        "PORT",
        "HOST",
        "_URL",
        "_REGION",
        "_BUCKET",
        "_ENV",
        "LOG_LEVEL",
        "TZ",
        "LANG",
    ];
    if plain.iter().any(|m| n.contains(m) || n == *m) {
        return Suggestion::Public;
    }
    // Long opaque values are more likely secrets than config.
    if value.len() >= 24 && !value.contains(' ') && !value.contains('/') {
        return Suggestion::Review;
    }
    Suggestion::Public
}

/// Render a `.env.example`: PUBLIC values verbatim, SECRET names with empty values.
pub fn render_example(vars: &[Variable]) -> String {
    let mut out = String::from("# Generated by EnvEnb. Secrets are intentionally blank.\n");
    for v in vars {
        match v.kind {
            VariableKind::Public => {
                let value = v.value.clone().unwrap_or_default();
                if value.chars().any(|c| c.is_whitespace() || c == '#' || c == '"') {
                    out.push_str(&format!("{}=\"{}\"\n", v.name, value.replace('"', "\\\"")));
                } else {
                    out.push_str(&format!("{}={}\n", v.name, value));
                }
            }
            VariableKind::Secret => out.push_str(&format!("{}=\n", v.name)),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_common_forms() {
        let text = r#"
# comment
NODE_ENV=development
export PORT=3000
APP_NAME="Env Fish" # trailing
QUOTED='single # not comment'
ESC="line1\nline2"
EMPTY=
BAD LINE
1BAD=x
"#;
        let (entries, invalid) = parse(text);
        let get = |n: &str| entries.iter().find(|e| e.name == n).map(|e| e.value.clone());
        assert_eq!(get("NODE_ENV").as_deref(), Some("development"));
        assert_eq!(get("PORT").as_deref(), Some("3000"));
        assert_eq!(get("APP_NAME").as_deref(), Some("Env Fish"));
        assert_eq!(get("QUOTED").as_deref(), Some("single # not comment"));
        assert_eq!(get("ESC").as_deref(), Some("line1\nline2"));
        assert_eq!(get("EMPTY").as_deref(), Some(""));
        assert_eq!(invalid, vec![9, 10]);
    }

    #[test]
    fn classification_heuristics() {
        assert_eq!(classify("NEXT_PUBLIC_API_KEY", "x"), Suggestion::Public);
        assert_eq!(classify("OPENAI_API_KEY", "sk-..."), Suggestion::Secret);
        assert_eq!(classify("SUPABASE_SECRET_KEY", "x"), Suggestion::Secret);
        assert_eq!(classify("GITHUB_TOKEN", "x"), Suggestion::Secret);
        assert_eq!(
            classify("DATABASE_URL", "postgres://user:pw@host/db"),
            Suggestion::Secret
        );
        assert_eq!(classify("APP_URL", "http://localhost:3000"), Suggestion::Public);
        assert_eq!(classify("STRIPE_KEY", "x"), Suggestion::Review);
        assert_eq!(classify("AWS_REGION", "ap-northeast-1"), Suggestion::Public);
    }

    #[test]
    fn example_blanks_secrets() {
        let now = chrono::Utc::now();
        let mk = |name: &str, kind, value: Option<&str>| Variable {
            id: "i".into(),
            environment_id: "e".into(),
            name: name.into(),
            kind,
            value: value.map(String::from),
            created_at: now,
            updated_at: now,
        };
        let out = render_example(&[
            mk("APP_URL", VariableKind::Public, Some("http://x")),
            mk("OPENAI_API_KEY", VariableKind::Secret, None),
        ]);
        assert!(out.contains("APP_URL=http://x\n"));
        assert!(out.contains("OPENAI_API_KEY=\n"));
    }
}

// ---------------------------------------------------------------------------
// .gitignore maintenance
// ---------------------------------------------------------------------------

/// Outcome of [`ensure_gitignored`].
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize)]
pub struct GitignoreReport {
    /// `.gitignore` that was inspected or written.
    pub path: String,
    /// Patterns appended this time (empty when everything was already covered).
    pub added: Vec<String>,
    /// Patterns that were already present.
    pub already: Vec<String>,
}

/// Make sure `patterns` (e.g. `.env.local`) are listed in `<repo_root>/.gitignore`,
/// creating the file if needed. Idempotent: existing lines are respected, and a
/// `!.env.example` exception is kept so templates stay committable.
pub fn ensure_gitignored(repo_root: &std::path::Path, patterns: &[&str]) -> std::io::Result<GitignoreReport> {
    let path = repo_root.join(".gitignore");
    let existing = std::fs::read_to_string(&path).unwrap_or_default();
    let lines: Vec<&str> = existing.lines().map(str::trim).collect();
    let covered = |p: &str| {
        let bare = p.trim_start_matches('/');
        lines.iter().any(|l| {
            let l = l.trim_start_matches('/');
            l == bare
                || l == format!("{bare}*")
                || (l == ".env*" && bare.starts_with(".env"))
                || (l == ".env.*" && bare.starts_with(".env."))
        })
    };
    let mut added = Vec::new();
    let mut already = Vec::new();
    for p in patterns {
        if covered(p) {
            already.push(p.to_string());
        } else {
            added.push(p.to_string());
        }
    }
    if !added.is_empty() {
        let mut out = existing.clone();
        if !out.is_empty() && !out.ends_with('\n') {
            out.push('\n');
        }
        if !out.is_empty() {
            out.push('\n');
        }
        out.push_str("# EnvEnb: local env files (values live in the EnvEnb vault)\n");
        for p in &added {
            out.push_str(p);
            out.push('\n');
        }
        if !lines.contains(&"!.env.example") {
            out.push_str("!.env.example\n");
        }
        std::fs::write(&path, out)?;
    }
    Ok(GitignoreReport {
        path: path.display().to_string(),
        added,
        already,
    })
}

/// Repository root for `dir` (via `git rev-parse`), if it is inside a git work tree.
pub fn git_root(dir: &std::path::Path) -> Option<std::path::PathBuf> {
    let out = std::process::Command::new("git")
        .args(["rev-parse", "--show-toplevel"])
        .current_dir(dir)
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let s = String::from_utf8_lossy(&out.stdout).trim().to_string();
    (!s.is_empty()).then(|| std::path::PathBuf::from(s))
}

#[cfg(test)]
mod gitignore_tests {
    use super::*;

    #[test]
    fn appends_once_and_keeps_example_exception() {
        let dir = tempfile::tempdir().unwrap();
        let r1 = ensure_gitignored(dir.path(), &[".env.local"]).unwrap();
        assert_eq!(r1.added, vec![".env.local"]);
        let text = std::fs::read_to_string(dir.path().join(".gitignore")).unwrap();
        assert!(text.contains(".env.local\n") && text.contains("!.env.example"));

        let r2 = ensure_gitignored(dir.path(), &[".env.local", ".env"]).unwrap();
        assert_eq!(r2.already, vec![".env.local"]);
        assert_eq!(r2.added, vec![".env"]);
        let text = std::fs::read_to_string(dir.path().join(".gitignore")).unwrap();
        assert_eq!(text.matches("!.env.example").count(), 1);
        assert_eq!(text.matches(".env.local").count(), 1);
    }

    #[test]
    fn wildcard_lines_count_as_coverage() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join(".gitignore"), "node_modules\n.env*\n").unwrap();
        let r = ensure_gitignored(dir.path(), &[".env.local"]).unwrap();
        assert!(r.added.is_empty() && r.already == vec![".env.local"]);
    }
}

// ---------------------------------------------------------------------------
// Removing dotenv files that EnvEnb already holds
// ---------------------------------------------------------------------------

/// Is `name` a dotenv file we would consider deleting? Templates are never touched.
pub fn is_dotenv_filename(name: &str) -> bool {
    (name == ".env" || name.starts_with(".env."))
        && !name.ends_with(".example")
        && !name.ends_with(".sample")
        && !name.ends_with(".template")
}

/// Names in `text` that are **not** among `known` (variables stored in EnvEnb).
/// Empty result means the file is fully covered and safe to delete.
pub fn uncovered_names(text: &str, known: &std::collections::HashSet<String>) -> Vec<String> {
    let (entries, _) = parse(text);
    entries
        .into_iter()
        .map(|e| e.name)
        .filter(|n| !known.contains(n))
        .collect()
}

/// Outcome of trying to remove one dotenv file.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize)]
#[serde(tag = "status", rename_all = "snake_case")]
pub enum RemoveOutcome {
    Removed { path: String, variables: usize },
    Kept { path: String, uncovered: Vec<String> },
    NotDotenv { path: String },
}

/// Delete `path` only if it is a dotenv file whose every variable is in `known`.
pub fn remove_if_covered(
    path: &std::path::Path,
    known: &std::collections::HashSet<String>,
) -> std::io::Result<RemoveOutcome> {
    let display = path.display().to_string();
    let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
    if !is_dotenv_filename(name) {
        return Ok(RemoveOutcome::NotDotenv { path: display });
    }
    let text = std::fs::read_to_string(path)?;
    let uncovered = uncovered_names(&text, known);
    if !uncovered.is_empty() {
        return Ok(RemoveOutcome::Kept {
            path: display,
            uncovered,
        });
    }
    let variables = parse(&text).0.len();
    std::fs::remove_file(path)?;
    Ok(RemoveOutcome::Removed {
        path: display,
        variables,
    })
}

/// Dotenv files directly inside `dir` (not recursive) that EnvEnb might clean up.
pub fn dotenv_files_in(dir: &std::path::Path) -> Vec<std::path::PathBuf> {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut out: Vec<_> = entries
        .flatten()
        .map(|e| e.path())
        .filter(|p| {
            p.is_file()
                && p.file_name()
                    .and_then(|n| n.to_str())
                    .is_some_and(is_dotenv_filename)
        })
        .collect();
    out.sort();
    out
}

#[cfg(test)]
mod filename_tests {
    use super::*;

    /// `clean` deletes whatever this accepts, so the template names must never
    /// be treated as real dotenv files: they are meant to be committed.
    #[test]
    fn real_dotenv_files_are_recognised() {
        for name in [".env", ".env.local", ".env.production", ".env.development.local"] {
            assert!(is_dotenv_filename(name), "{name} should be a dotenv file");
        }
    }

    #[test]
    fn templates_and_unrelated_files_are_not() {
        for name in [
            ".env.example",
            ".env.sample",
            ".env.template",
            ".environment",
            "env",
            "env.local",
            "docker.env",
            "README.md",
        ] {
            assert!(!is_dotenv_filename(name), "{name} should not be a dotenv file");
        }
    }
}

#[cfg(test)]
mod remove_tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn only_fully_covered_dotenv_files_are_removed() {
        let dir = tempfile::tempdir().unwrap();
        let env = dir.path().join(".env.local");
        std::fs::write(&env, "A=1\nB=2\n").unwrap();
        let example = dir.path().join(".env.example");
        std::fs::write(&example, "A=\n").unwrap();

        let partial: HashSet<String> = ["A".to_string()].into();
        assert!(
            matches!(remove_if_covered(&env, &partial).unwrap(), RemoveOutcome::Kept { uncovered, .. } if uncovered == vec!["B"])
        );
        assert!(env.exists());

        let full: HashSet<String> = ["A".to_string(), "B".to_string()].into();
        assert!(matches!(
            remove_if_covered(&env, &full).unwrap(),
            RemoveOutcome::Removed { variables: 2, .. }
        ));
        assert!(!env.exists());

        assert!(matches!(
            remove_if_covered(&example, &full).unwrap(),
            RemoveOutcome::NotDotenv { .. }
        ));
        assert!(example.exists());
        assert_eq!(dotenv_files_in(dir.path()), Vec::<std::path::PathBuf>::new());
    }
}

#[cfg(test)]
mod worktree_tests {
    use super::*;
    use std::process::Command;

    fn git(dir: &std::path::Path, args: &[&str]) -> bool {
        Command::new("git")
            .args(args)
            .current_dir(dir)
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
    }

    /// A linked worktree has no `.git` directory of its own — only a `.git`
    /// *file* pointing into the main repository. `git_root` must still report
    /// the worktree's own root, so `.gitignore` is written next to the files
    /// the user is actually working on rather than in the main checkout.
    #[test]
    fn a_linked_worktree_resolves_to_its_own_root() {
        let tmp = tempfile::tempdir().unwrap();
        let main = tmp.path().join("main");
        std::fs::create_dir_all(&main).unwrap();

        if !git(&main, &["init", "-q", "."]) {
            return; // no usable git in this environment
        }
        git(&main, &["config", "user.email", "test@example.com"]);
        git(&main, &["config", "user.name", "test"]);
        std::fs::write(main.join("README"), b"x").unwrap();
        git(&main, &["add", "-A"]);
        if !git(&main, &["commit", "-qm", "init"]) {
            return;
        }

        let wt = tmp.path().join("wt");
        if !git(&main, &["worktree", "add", "-q", wt.to_str().unwrap(), "-b", "feature"]) {
            return;
        }
        // A linked worktree carries a .git file, not a directory.
        assert!(wt.join(".git").is_file(), "expected a linked worktree");

        let got = git_root(&wt).expect("worktree should resolve to a git root");
        assert_eq!(
            got.canonicalize().unwrap(),
            wt.canonicalize().unwrap(),
            "git_root must return the worktree's own root, not the main checkout"
        );

        // And .gitignore must land inside the worktree.
        ensure_gitignored(&got, &[".env.local"]).unwrap();
        assert!(wt.join(".gitignore").is_file());
        assert!(!main.join(".gitignore").exists());
    }
}
